server:
  port: 1002
spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: nacos.vegetarianlefty.com:8848
      config:
        group: JAVA
        namespace: ""
      discovery:
        group: JAVA
        namespace: ""
dubbo:
  application:
    name: dubbo-consumer
  scan:
    base-packages: com.vegetarianlefty
  protocols:
    dubbo:
      name: dubbo
      host: ${spring.cloud.client.ip-address}
      port: -1
      serialization: kryo
  registry:
    id: zk-registry
    address: zookeeper://zk.vegetarianlefty.com:2181
  config-center:
    address: zookeeper://zk.vegetarianlefty.com:2181
  metadata-report:
    address: zookeeper://zk.vegetarianlefty.com:2181
  consumer:
    check: false